"use client";
import { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api-client";
import type { BlogComment, BlogPost, Challenge, CommunityEvent, Message } from "@/lib/schema";
import { Field } from "./Fields";

type Resource = "blog" | "challenges" | "events" | "comments" | "applications";
const inputDate = (value: number | null) => value ? new Date(value - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : "";
const timestamp = (value: string) => value ? new Date(value).getTime() : null;
const idPath = (resource: Resource, id?: string) => `/api/admin/platform/${resource}${id ? `/${id}` : ""}`;

function useItems<T>(resource: Resource) {
  const [items, setItems] = useState<T[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = useCallback(async () => {
    setLoading(true);
    try { setItems((await api<{ items: T[] }>(idPath(resource))).items); setError(""); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load records."); }
    finally { setLoading(false); }
  }, [resource]);
  useEffect(() => {
    let cancelled = false;
    void api<{ items: T[] }>(idPath(resource)).then((result) => { if (!cancelled) { setItems(result.items); setError(""); } }).catch((reason) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "Unable to load records."); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [resource]);
  return { items, loading, error, setError, load };
}

function ManagerLayout({ title, description, list, children, error, notice }: { title: string; description: string; list: React.ReactNode; children: React.ReactNode; error?: string; notice?: string }) {
  return <div className="workspace-panel"><div className="editor-heading"><div><span className="eyebrow">PUBLISHING WORKFLOW</span><h2>{title}</h2><p className="muted">{description}</p></div></div>{error && <p className="alert" role="alert">{error}</p>}{notice && <p className="notice" role="status">{notice}</p>}<div className="platform-layout"><aside className="platform-list">{list}</aside><section className="platform-editor">{children}</section></div></div>;
}

type BlogForm = { slug: string; title: string; excerpt: string; content: string; coverImageUrl: string; tags: string[]; status: "draft" | "published" };
const emptyBlog: BlogForm = { slug: "", title: "", excerpt: "", content: "", coverImageUrl: "", tags: [], status: "draft" };
function BlogManager({ readOnly }: { readOnly: boolean }) {
  const state = useItems<BlogPost>("blog"), [selected, setSelected] = useState<string | null>(null), [form, setForm] = useState<typeof emptyBlog>(emptyBlog), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const choose = (item: BlogPost) => { setSelected(item.id); setForm({ slug: item.slug, title: item.title, excerpt: item.excerpt, content: item.content, coverImageUrl: item.coverImageUrl, tags: item.tags, status: item.status }); setNotice(""); };
  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setBusy(true); state.setError(""); try { await api(idPath("blog", selected ?? undefined), selected ? "PATCH" : "POST", form); await state.load(); setNotice(selected ? "Article updated." : "Article created."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to save the article."); } finally { setBusy(false); } }
  async function remove() { if (!selected || !window.confirm("Delete this article and all of its comments?")) return; setBusy(true); try { await api(idPath("blog", selected), "DELETE"); setSelected(null); setForm(emptyBlog); await state.load(); setNotice("Article deleted."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to delete the article."); } finally { setBusy(false); } }
  const list = <><button className="platform-new" onClick={() => { setSelected(null); setForm(emptyBlog); }}>New article +</button>{state.loading ? <p className="empty-inline">Loading…</p> : state.items.map((item) => <button key={item.id} className={selected === item.id ? "platform-record active" : "platform-record"} onClick={() => choose(item)}><strong>{item.title}</strong><span>{item.status} · {item.slug}</span></button>)}</>;
  return <ManagerLayout title="Blog" description="Draft and publish long-form field notes. Only published articles appear publicly." list={list} error={state.error} notice={notice}><fieldset disabled={readOnly || busy} className="platform-form"><div className="fields-grid"><Field label="Title" value={form.title} onChange={(value) => set("title", value)} /><Field label="Slug" value={form.slug} onChange={(value) => set("slug", value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))} /></div><Field label="Excerpt" value={form.excerpt} multiline onChange={(value) => set("excerpt", value)} /><Field label="Article content" value={form.content} multiline onChange={(value) => set("content", value)} /><div className="fields-grid"><Field label="Cover image URL" value={form.coverImageUrl} onChange={(value) => set("coverImageUrl", value)} /><Field label="Tags (comma separated)" value={form.tags.join(", ")} onChange={(value) => set("tags", value.split(",").map((part) => part.trim()).filter(Boolean))} /><label className="field">Status<select value={form.status} onChange={(event) => set("status", event.target.value as "draft" | "published")}><option value="draft">Draft</option><option value="published">Published</option></select></label></div><div className="button-row"><button className="primary" type="button" onClick={save}>{busy ? "Saving…" : selected ? "Save article" : "Create article"}</button>{selected && <button className="danger-text" type="button" onClick={remove}>Delete article</button>}</div></fieldset></ManagerLayout>;
}

type ChallengeForm = { slug: string; title: string; description: string; category: string; difficulty: "beginner" | "intermediate" | "advanced"; resourceUrl: string; opensAt: string; closesAt: string; status: "draft" | "published" | "closed"; flag: string };
type ChallengeAttempt = { id: string; uid: string; handle: string; correct: boolean; createdAt: number };
const emptyChallenge: ChallengeForm = { slug: "", title: "", description: "", category: "Web", difficulty: "intermediate", resourceUrl: "", opensAt: inputDate(Date.now()), closesAt: "", status: "draft", flag: "" };
function ChallengeManager({ readOnly }: { readOnly: boolean }) {
  const state = useItems<Challenge>("challenges"), [selected, setSelected] = useState<string | null>(null), [form, setForm] = useState(emptyChallenge), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const [attempts, setAttempts] = useState<ChallengeAttempt[]>([]), [attemptsLoading, setAttemptsLoading] = useState(false);
  async function loadAttempts(id: string) {
    setAttemptsLoading(true);
    try { setAttempts((await api<{ items: ChallengeAttempt[] }>(`/api/admin/platform/challenges/${id}/attempts`)).items); }
    catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to load challenge attempts."); }
    finally { setAttemptsLoading(false); }
  }
  const choose = (item: Challenge) => { setSelected(item.id); setForm({ slug: item.slug, title: item.title, description: item.description, category: item.category, difficulty: item.difficulty, resourceUrl: item.resourceUrl, opensAt: inputDate(item.opensAt), closesAt: inputDate(item.closesAt), status: item.status, flag: "" }); setNotice(""); void loadAttempts(item.id); };
  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setBusy(true); state.setError(""); try { const payload = { ...form, opensAt: timestamp(form.opensAt), closesAt: timestamp(form.closesAt) }; await api(idPath("challenges", selected ?? undefined), selected ? "PATCH" : "POST", payload); await state.load(); set("flag", ""); setNotice(selected ? "Challenge updated. A blank flag kept the existing secret." : "Challenge created."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to save the challenge."); } finally { setBusy(false); } }
  async function remove() { if (!selected || !window.confirm("Delete this challenge, its attempts, solves and secret flag?")) return; setBusy(true); try { await api(idPath("challenges", selected), "DELETE"); setSelected(null); setForm(emptyChallenge); setAttempts([]); await state.load(); setNotice("Challenge deleted."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to delete the challenge."); } finally { setBusy(false); } }
  const list = <><button className="platform-new" onClick={() => { setSelected(null); setForm({ ...emptyChallenge, opensAt: inputDate(Date.now()) }); setAttempts([]); }}>New challenge +</button>{state.loading ? <p className="empty-inline">Loading…</p> : state.items.map((item) => <button key={item.id} className={selected === item.id ? "platform-record active" : "platform-record"} onClick={() => choose(item)}><strong>{item.title}</strong><span>{item.status} · {item.difficulty}</span></button>)}</>;
  return <ManagerLayout title="Weekly challenges" description="Publish one active challenge, keep its flag private and inspect every submission." list={list} error={state.error} notice={notice}>
    <fieldset disabled={readOnly || busy} className="platform-form"><div className="fields-grid"><Field label="Title" value={form.title} onChange={(value) => set("title", value)} /><Field label="Slug" value={form.slug} onChange={(value) => set("slug", value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""))} /><Field label="Category" value={form.category} onChange={(value) => set("category", value)} /><label className="field">Difficulty<select value={form.difficulty} onChange={(event) => set("difficulty", event.target.value as typeof form.difficulty)}><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label></div><Field label="Challenge brief" value={form.description} multiline onChange={(value) => set("description", value)} /><div className="fields-grid"><Field label="Resource URL" value={form.resourceUrl} onChange={(value) => set("resourceUrl", value)} /><Field label={selected ? "New flag (leave blank to keep current)" : "Flag"} value={form.flag} onChange={(value) => set("flag", value)} /><Field label="Opens at" type="datetime-local" value={form.opensAt} onChange={(value) => set("opensAt", value)} /><Field label="Closes at (optional)" type="datetime-local" value={form.closesAt} onChange={(value) => set("closesAt", value)} /><label className="field">Status<select value={form.status} onChange={(event) => set("status", event.target.value as typeof form.status)}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select></label></div><div className="button-row"><button className="primary" type="button" onClick={save}>{busy ? "Saving…" : selected ? "Save challenge" : "Create challenge"}</button>{selected && <button className="danger-text" type="button" onClick={remove}>Delete challenge</button>}</div></fieldset>
    {selected && <section className="attempt-inspector"><div className="attempt-heading"><div><span className="eyebrow">SUBMISSION LOG</span><h3>Attempts</h3></div><span className="badge">{attempts.filter((item) => item.correct).length} solves / {attempts.length} attempts</span></div>{attemptsLoading ? <p className="empty-inline">Loading attempts…</p> : attempts.length ? <div className="attempt-table">{attempts.map((item) => <div key={item.id}><strong>{item.handle}</strong><span className={item.correct ? "attempt-result correct" : "attempt-result"}>{item.correct ? "SOLVED" : "INCORRECT"}</span><time>{new Date(item.createdAt).toLocaleString()}</time></div>)}</div> : <p className="empty-inline">No submissions yet.</p>}</section>}
  </ManagerLayout>;
}

type EventForm = { title: string; description: string; location: string; startsAt: string; endsAt: string; registrationUrl: string; status: "draft" | "published" | "cancelled" };
const emptyEvent: EventForm = { title: "", description: "", location: "Online", startsAt: inputDate(Date.now()), endsAt: "", registrationUrl: "", status: "draft" };
function EventManager({ readOnly }: { readOnly: boolean }) {
  const state = useItems<CommunityEvent>("events"), [selected, setSelected] = useState<string | null>(null), [form, setForm] = useState(emptyEvent), [busy, setBusy] = useState(false), [notice, setNotice] = useState("");
  const choose = (item: CommunityEvent) => { setSelected(item.id); setForm({ title: item.title, description: item.description, location: item.location, startsAt: inputDate(item.startsAt), endsAt: inputDate(item.endsAt), registrationUrl: item.registrationUrl, status: item.status }); setNotice(""); };
  const set = <K extends keyof typeof form>(key: K, value: (typeof form)[K]) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setBusy(true); state.setError(""); try { await api(idPath("events", selected ?? undefined), selected ? "PATCH" : "POST", { ...form, startsAt: timestamp(form.startsAt), endsAt: timestamp(form.endsAt) }); await state.load(); setNotice(selected ? "Event updated." : "Event created."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to save the event."); } finally { setBusy(false); } }
  async function remove() { if (!selected || !window.confirm("Delete this event?")) return; setBusy(true); try { await api(idPath("events", selected), "DELETE"); setSelected(null); setForm(emptyEvent); await state.load(); setNotice("Event deleted."); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to delete the event."); } finally { setBusy(false); } }
  const list = <><button className="platform-new" onClick={() => { setSelected(null); setForm({ ...emptyEvent, startsAt: inputDate(Date.now()) }); }}>New event +</button>{state.loading ? <p className="empty-inline">Loading…</p> : state.items.map((item) => <button key={item.id} className={selected === item.id ? "platform-record active" : "platform-record"} onClick={() => choose(item)}><strong>{item.title}</strong><span>{item.status} · {new Date(item.startsAt).toLocaleDateString()}</span></button>)}</>;
  return <ManagerLayout title="Events" description="Schedule public competitions, sessions and appearances." list={list} error={state.error} notice={notice}><fieldset disabled={readOnly || busy} className="platform-form"><Field label="Title" value={form.title} onChange={(value) => set("title", value)} /><Field label="Description" value={form.description} multiline onChange={(value) => set("description", value)} /><div className="fields-grid"><Field label="Location" value={form.location} onChange={(value) => set("location", value)} /><Field label="Registration or details URL" value={form.registrationUrl} onChange={(value) => set("registrationUrl", value)} /><Field label="Starts at" type="datetime-local" value={form.startsAt} onChange={(value) => set("startsAt", value)} /><Field label="Ends at (optional)" type="datetime-local" value={form.endsAt} onChange={(value) => set("endsAt", value)} /><label className="field">Status<select value={form.status} onChange={(event) => set("status", event.target.value as typeof form.status)}><option value="draft">Draft</option><option value="published">Published</option><option value="cancelled">Cancelled</option></select></label></div><div className="button-row"><button className="primary" type="button" onClick={save}>{busy ? "Saving…" : selected ? "Save event" : "Create event"}</button>{selected && <button className="danger-text" type="button" onClick={remove}>Delete event</button>}</div></fieldset></ManagerLayout>;
}

function CommentManager({ readOnly }: { readOnly: boolean }) {
  const state = useItems<BlogComment>("comments"), [busy, setBusy] = useState("");
  async function moderate(item: BlogComment, status: "approved" | "hidden") { setBusy(item.id); try { await api(`/api/admin/platform/comments/${item.postId}/${item.id}`, "PATCH", { status }); await state.load(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to moderate the comment."); } finally { setBusy(""); } }
  async function remove(item: BlogComment) { if (!window.confirm("Delete this comment permanently?")) return; setBusy(item.id); try { await api(`/api/admin/platform/comments/${item.postId}/${item.id}`, "DELETE"); await state.load(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to delete the comment."); } finally { setBusy(""); } }
  return <div className="workspace-panel"><div className="editor-heading"><div><span className="eyebrow">MODERATION QUEUE</span><h2>Comments</h2><p className="muted">Only approved comments appear on public articles.</p></div><span className="badge">{state.items.filter((item) => item.status === "pending").length} pending</span></div>{state.error && <p className="alert">{state.error}</p>}<div className="moderation-list">{state.loading ? <p>Loading…</p> : state.items.length ? state.items.map((item) => <article key={item.id}><div><strong>{item.handle}</strong><span>{item.status} · {new Date(item.createdAt).toLocaleString()}</span></div><p>{item.body}</p><div className="button-row"><button disabled={readOnly || busy === item.id} onClick={() => moderate(item, "approved")}>Approve</button><button disabled={readOnly || busy === item.id} onClick={() => moderate(item, "hidden")}>Hide</button><button className="danger-text" disabled={readOnly || busy === item.id} onClick={() => remove(item)}>Delete</button></div></article>) : <p className="empty-inline">No comments yet.</p>}</div></div>;
}

type Application = Message & { kind?: string; application?: { handle?: string; discipline?: string; portfolioUrl?: string } };
function ApplicationManager({ readOnly }: { readOnly: boolean }) {
  const state = useItems<Application>("applications"), [selected, setSelected] = useState<Application | null>(null), [status, setStatus] = useState<Message["status"]>("new"), [notes, setNotes] = useState(""), [busy, setBusy] = useState(false);
  function choose(item: Application) { setSelected(item); setStatus(item.status); setNotes(item.notes); }
  async function save() { if (!selected) return; setBusy(true); try { await api(`/api/admin/platform/applications/${selected.id}`, "PATCH", { status, notes }); await state.load(); } catch (reason) { state.setError(reason instanceof Error ? reason.message : "Unable to update the application."); } finally { setBusy(false); } }
  const list = <>{state.loading ? <p className="empty-inline">Loading…</p> : state.items.map((item) => <button key={item.id} className={selected?.id === item.id ? "platform-record active" : "platform-record"} onClick={() => choose(item)}><strong>{item.name}</strong><span>{item.status} · {item.application?.discipline}</span></button>)}</>;
  return <ManagerLayout title="Joining applications" description="Review applications submitted through the public joining page." list={list} error={state.error}>{selected ? <div className="application-detail"><h3>{selected.name}</h3><a href={`mailto:${selected.email}`}>{selected.email}</a><dl><dt>Handle</dt><dd>{selected.application?.handle}</dd><dt>Discipline</dt><dd>{selected.application?.discipline}</dd><dt>Portfolio</dt><dd>{selected.application?.portfolioUrl ? <a href={selected.application.portfolioUrl} target="_blank" rel="noreferrer">Open link ↗</a> : "Not provided"}</dd></dl><p>{selected.message}</p><fieldset disabled={readOnly || busy} className="platform-form"><label className="field">Status<select value={status} onChange={(event) => setStatus(event.target.value as Message["status"])}><option value="new">New</option><option value="read">Read</option><option value="archived">Archived</option></select></label><Field label="Internal notes" value={notes} multiline onChange={setNotes} /><button className="primary" onClick={save}>Save application</button></fieldset></div> : <p className="empty-inline">Choose an application to review.</p>}</ManagerLayout>;
}

export function PlatformManager({ resource, readOnly }: { resource: Resource; readOnly: boolean }) {
  if (resource === "blog") return <BlogManager readOnly={readOnly} />;
  if (resource === "challenges") return <ChallengeManager readOnly={readOnly} />;
  if (resource === "events") return <EventManager readOnly={readOnly} />;
  if (resource === "comments") return <CommentManager readOnly={readOnly} />;
  return <ApplicationManager readOnly={readOnly} />;
}
