"use client";
import type { SiteContent } from "@/lib/schema";
import { Field, StringFields, pretty } from "./Fields";

export function SettingsEditor({ site, onChange, readOnly }: { site: SiteContent; onChange: (value: SiteContent) => void; readOnly: boolean }) {
  const settings = site.settings;
  const update = (patch: Partial<SiteContent["settings"]>) => onChange({ ...site, settings: { ...settings, ...patch } });
  return <div className="settings-editor"><div className="editor-heading"><div><span className="eyebrow">SITE-WIDE</span><h2>Settings</h2><p className="muted">These changes are included in the same draft as your sections.</p></div></div><fieldset disabled={readOnly}>
    <div className="form-section"><h3>Identity & search</h3><div className="fields-grid">{(["name", "registrationMark", "headerLine", "title", "publicUrl", "copyright"] as const).map((key) => <Field key={key} label={pretty(key)} value={settings[key]} onChange={(value) => update({ [key]: value })} />)}</div><Field label="Search description" value={settings.description} multiline onChange={(value) => update({ description: value })} /></div>
    {(["navigation", "footerLinks"] as const).map((group) => <div className="form-section" key={group}><div className="subheading"><h3>{pretty(group)}</h3><button onClick={() => update({ [group]: [...settings[group], { label: "New link", href: `#${site.sections[0].id}` }] })} disabled={settings[group].length >= 20}>Add link +</button></div><p className="muted">Section links use # followed by the section ID. Links to hidden sections stay out of the public navigation.</p>{settings[group].map((link, index) => <div className="link-row" key={index}><Field label="Label" value={link.label} onChange={(value) => update({ [group]: settings[group].map((entry, i) => i === index ? { ...entry, label: value } : entry) })} /><Field label="Destination" value={link.href} onChange={(value) => update({ [group]: settings[group].map((entry, i) => i === index ? { ...entry, href: value } : entry) })} /><button aria-label={`Move ${link.label} up`} disabled={index === 0} onClick={() => { const links = [...settings[group]]; [links[index - 1], links[index]] = [links[index], links[index - 1]]; update({ [group]: links }); }}>↑</button><button className="danger-text" onClick={() => update({ [group]: settings[group].filter((_, i) => i !== index) })}>Remove</button></div>)}</div>)}
    <div className="form-section"><h3>Contact form</h3><label className="toggle"><input type="checkbox" checked={settings.contact.enabled} onChange={(event) => update({ contact: { ...settings.contact, enabled: event.target.checked } })} />Accept messages</label><StringFields values={Object.fromEntries(Object.entries(settings.contact).filter(([, value]) => typeof value === "string")) as Record<string, string>} onChange={(key, value) => update({ contact: { ...settings.contact, [key]: value } })} /></div>
    <div className="form-section"><h3>Site controls & labels</h3><StringFields values={settings.labels} onChange={(key, value) => update({ labels: { ...settings.labels, [key]: value } })} /></div>
    <div className="form-section"><h3>Theme colors</h3><p className="muted">The 3D animation keeps its original art direction.</p><div className="color-fields">{Object.entries(settings.theme).map(([key, value]) => <Field key={key} label={pretty(key)} type="color" value={value} onChange={(next) => update({ theme: { ...settings.theme, [key]: next } })} />)}</div></div>
  </fieldset></div>;
}
